# Generated by Django 5.2.7 on 2025-12-04 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0007_worker_curriculum'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BowelMovementRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('time', models.TimeField(verbose_name='Hora')),
                ('type', models.CharField(choices=[('normal', 'Normal'), ('diarrea', 'Diarrea'), ('estreñimiento', 'Estreñimiento'), ('sangre', 'Con sangre')], max_length=20, verbose_name='Tipo de deposición')),
                ('consistency', models.CharField(blank=True, choices=[('tipo1', 'Tipo 1 - Trozos duros separados'), ('tipo2', 'Tipo 2 - Con forma de salchicha grumosa'), ('tipo3', 'Tipo 3 - Con forma de salchicha con grietas'), ('tipo4', 'Tipo 4 - Con forma de salchicha lisa'), ('tipo5', 'Tipo 5 - Trozos blandos con bordes definidos'), ('tipo6', 'Tipo 6 - Trozos blandos con bordes irregulares'), ('tipo7', 'Tipo 7 - Líquida sin trozos')], max_length=20, verbose_name='Consistencia')),
                ('color', models.CharField(blank=True, choices=[('marron', 'Marrón'), ('verde', 'Verde'), ('amarillo', 'Amarillo'), ('negro', 'Negro'), ('rojo', 'Rojo')], max_length=20, verbose_name='Color')),
                ('quantity', models.CharField(blank=True, max_length=50, verbose_name='Cantidad')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bowel_registries', to='management.resident', verbose_name='Residente')),
            ],
            options={
                'verbose_name': 'Registro de Deposición',
                'verbose_name_plural': 'Registros de Deposición',
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.CreateModel(
            name='FoodRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('time', models.TimeField(verbose_name='Hora')),
                ('solid_intake', models.CharField(blank=True, choices=[('nada', 'Nada'), ('poco', 'Poco (25%)'), ('medio', 'Medio (50%)'), ('bastante', 'Bastante (75%)'), ('todo', 'Todo (100%)')], max_length=20, verbose_name='Ingesta de sólidos')),
                ('first_course', models.CharField(blank=True, max_length=200, verbose_name='Primer plato')),
                ('second_course', models.CharField(blank=True, max_length=200, verbose_name='Segundo plato')),
                ('dessert', models.CharField(blank=True, max_length=200, verbose_name='Postre')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_registries', to='management.resident', verbose_name='Residente')),
            ],
            options={
                'verbose_name': 'Registro de Alimentación',
                'verbose_name_plural': 'Registros de Alimentación',
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.CreateModel(
            name='HydrationRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('time', models.TimeField(verbose_name='Hora')),
                ('liquid_type', models.CharField(choices=[('agua', 'Agua'), ('zumo', 'Zumo'), ('leche', 'Leche'), ('cafe', 'Café'), ('te', 'Té'), ('otros', 'Otros')], max_length=20, verbose_name='Tipo de líquido')),
                ('quantity_ml', models.IntegerField(verbose_name='Cantidad (ml)')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hydration_registries', to='management.resident', verbose_name='Residente')),
            ],
            options={
                'verbose_name': 'Registro de Hidratación',
                'verbose_name_plural': 'Registros de Hidratación',
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.CreateModel(
            name='MedicationRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('time', models.TimeField(verbose_name='Hora')),
                ('medication_name', models.CharField(max_length=200, verbose_name='Nombre del medicamento')),
                ('dosage', models.CharField(max_length=100, verbose_name='Dosis')),
                ('route', models.CharField(blank=True, max_length=50, verbose_name='Vía de administración')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('administered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Administrado por')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_registries', to='management.resident', verbose_name='Residente')),
            ],
            options={
                'verbose_name': 'Registro de Medicación',
                'verbose_name_plural': 'Registros de Medicación',
                'ordering': ['-date', '-time'],
            },
        ),
    ]
