# Generated by Django 5.2.7 on 2025-12-05 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_delete_hydrationregistry'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodregistry',
            name='liquid_intake',
            field=models.CharField(blank=True, choices=[('desayuno', 'Desayuno'), ('comida', 'Comida'), ('merienda', 'Merienda'), ('cena', 'Cena')], max_length=20, verbose_name='Ingesta de líquidos'),
        ),
        migrations.AddField(
            model_name='foodregistry',
            name='quantity',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cantidad'),
        ),
    ]
