# Generated by Django 5.2.7 on 2025-12-05 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_worker_curriculum'),
        ('registry', '0003_foodregistry_liquid_intake_foodregistry_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panel', models.CharField(choices=[('sanitario', 'Sanitario'), ('general', 'General'), ('incidencia', 'Incidencia')], max_length=20, verbose_name='Panel')),
                ('type', models.CharField(choices=[('alimentacion', 'Alimentación'), ('medicacion', 'Medicación'), ('deposicion', 'Deposición')], max_length=20, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('abierto', 'Abierto'), ('cerrado', 'Cerrado')], default='abierto', max_length=20, verbose_name='Estado')),
                ('form_data', models.JSONField(blank=True, null=True, verbose_name='Datos del formulario')),
                ('notes', models.TextField(blank=True, verbose_name='Notas adicionales')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='management.resident', verbose_name='Residente')),
            ],
            options={
                'verbose_name': 'Anotación',
                'verbose_name_plural': 'Anotaciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
