# Generated by Django 5.2.7 on 2025-12-08 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0004_annotation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='type',
            field=models.CharField(choices=[('alimentacion', 'Alimentación'), ('medicacion', 'Medicación'), ('deposicion', 'Deposición'), ('caida', 'Caída')], max_length=20, verbose_name='Tipo'),
        ),
    ]
