# Generated by Django 5.2.7 on 2025-12-09 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0006_alter_annotation_panel_alter_annotation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='type',
            field=models.CharField(choices=[('alimentacion', 'Alimentación'), ('caida', 'Caída'), ('citaMedica', 'Cita médica'), ('urgencias', 'Derivación a urgencias'), ('general', 'General'), ('direccion', 'Dirección'), ('medicacion', 'Medicación'), ('deposicion', 'Deposición'), ('cuidados', 'Cuidados'), ('salida', 'Salida')], max_length=20, verbose_name='Tipo'),
        ),
    ]
