# Generated by Django 5.2.7 on 2025-11-25 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('first_surname', models.CharField(max_length=100, verbose_name='Primer apellido')),
                ('second_surname', models.CharField(blank=True, max_length=100, verbose_name='Segundo apellido')),
                ('nif_nie', models.CharField(max_length=20, unique=True, verbose_name='NIF/NIE')),
                ('birthdate', models.DateField(verbose_name='Fecha de nacimiento')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, verbose_name='Género')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('locality', models.CharField(blank=True, max_length=100, verbose_name='Localidad')),
                ('province', models.CharField(blank=True, max_length=100, verbose_name='Provincia')),
                ('country', models.CharField(default='España', max_length=100, verbose_name='País')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('social_security_number', models.CharField(blank=True, max_length=20, verbose_name='Número de Seguridad Social')),
                ('admission_date', models.DateField(auto_now_add=True, verbose_name='Fecha de ingreso')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Residente',
                'verbose_name_plural': 'Residentes',
                'ordering': ['first_surname', 'second_surname', 'name'],
            },
        ),
    ]
