# Generated by Django 5.2.7 on 2025-11-25 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('first_surname', models.CharField(max_length=100, verbose_name='Primer apellido')),
                ('second_surname', models.CharField(blank=True, max_length=100, verbose_name='Segundo apellido')),
                ('nif_nie', models.CharField(max_length=20, unique=True, verbose_name='NIF/NIE')),
                ('birthdate', models.DateField(verbose_name='Fecha de nacimiento')),
                ('gender', models.CharField(blank=True, choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer')], max_length=10, verbose_name='Género')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('locality', models.CharField(blank=True, max_length=100, verbose_name='Localidad')),
                ('province', models.CharField(blank=True, choices=[('Huesca', 'Huesca'), ('Teruel', 'Teruel'), ('Zaragoza', 'Zaragoza')], max_length=100, verbose_name='Provincia')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='País')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('social_security_number', models.CharField(blank=True, max_length=20, verbose_name='NSS')),
                ('account_number', models.CharField(blank=True, max_length=24, verbose_name='Número de cuenta')),
                ('disability_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Minusvalía(%)')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='workers/photos/', verbose_name='Foto de perfil')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='Fecha de contratación')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worker_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trabajador',
                'verbose_name_plural': 'Trabajadores',
                'ordering': ['first_surname', 'second_surname', 'name'],
            },
        ),
    ]
