# Generated by Django 5.2.7 on 2025-12-01 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Edad'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='gender',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name='Género'),
        ),
    ]
