# Generated by Django 5.2.7 on 2025-12-01 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_worker_age_alter_resident_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='age',
        ),
    ]
