# Generated by Django 5.2.7 on 2025-12-01 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_remove_worker_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='role',
            field=models.CharField(blank=True, choices=[('Coordinador', 'Coordinador'), ('Enfermero', 'Enfermero')], max_length=20, verbose_name='Rol'),
        ),
    ]
