# Generated by Django 5.2.7 on 2025-12-03 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_worker_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='allergies',
            field=models.TextField(blank=True, verbose_name='Alergias'),
        ),
        migrations.AddField(
            model_name='resident',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, verbose_name='Grupo Sanguíneo'),
        ),
        migrations.AddField(
            model_name='resident',
            name='chronic_diseases',
            field=models.TextField(blank=True, verbose_name='Enfermedades Crónicas'),
        ),
        migrations.AddField(
            model_name='resident',
            name='current_medications',
            field=models.TextField(blank=True, verbose_name='Medicación Actual'),
        ),
        migrations.AddField(
            model_name='resident',
            name='dependency_degree',
            field=models.CharField(blank=True, choices=[('grado_I', 'Grado I - Dependencia Moderada'), ('grado_II', 'Grado II - Dependencia Severa'), ('grado_III', 'Grado III - Gran Dependencia')], max_length=20, verbose_name='Grado de Dependencia'),
        ),
        migrations.AddField(
            model_name='resident',
            name='doctor_phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='Teléfono del Médico'),
        ),
        migrations.AddField(
            model_name='resident',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre Contacto Emergencia'),
        ),
        migrations.AddField(
            model_name='resident',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='Teléfono Emergencia'),
        ),
        migrations.AddField(
            model_name='resident',
            name='emergency_contact_relationship',
            field=models.CharField(blank=True, max_length=50, verbose_name='Relación'),
        ),
        migrations.AddField(
            model_name='resident',
            name='insurance_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Número de Póliza'),
        ),
        migrations.AddField(
            model_name='resident',
            name='medical_insurance',
            field=models.CharField(blank=True, max_length=100, verbose_name='Seguro Médico'),
        ),
        migrations.AddField(
            model_name='resident',
            name='mobility_level',
            field=models.CharField(blank=True, choices=[('autonomo', 'Autónomo'), ('ayuda_parcial', 'Ayuda Parcial'), ('silla_ruedas', 'Silla de Ruedas'), ('encamado', 'Encamado')], max_length=20, verbose_name='Nivel de Movilidad'),
        ),
        migrations.AddField(
            model_name='resident',
            name='primary_doctor',
            field=models.CharField(blank=True, max_length=100, verbose_name='Médico de Cabecera'),
        ),
        migrations.AddField(
            model_name='resident',
            name='uses_walker',
            field=models.BooleanField(default=False, verbose_name='Usa Andador'),
        ),
        migrations.AddField(
            model_name='resident',
            name='uses_wheelchair',
            field=models.BooleanField(default=False, verbose_name='Usa Silla de Ruedas'),
        ),
    ]
