# Generated by Django 5.2.7 on 2025-12-04 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_resident_allergies_resident_blood_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='curriculum',
            field=models.FileField(blank=True, null=True, upload_to='workers/curriculum/', verbose_name='Currículum'),
        ),
    ]
