# Generated by Django 5.2.7 on 2025-12-06 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_remove_worker_email_alter_worker_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='enable_bowel_registry',
            field=models.BooleanField(default=True, verbose_name='Habilitar Registro de Deposición'),
        ),
        migrations.AddField(
            model_name='resident',
            name='enable_food_registry',
            field=models.BooleanField(default=True, verbose_name='Habilitar Registro de Alimentación'),
        ),
        migrations.AddField(
            model_name='resident',
            name='enable_medication_registry',
            field=models.BooleanField(default=True, verbose_name='Habilitar Registro de Medicación'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='gender',
            field=models.CharField(blank=True, choices=[('H', 'Hombre'), ('M', 'Mujer')], max_length=10, verbose_name='Género'),
        ),
    ]
