# Generated by Django 5.2.7 on 2025-12-06 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_resident_enable_bowel_registry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='role',
            field=models.CharField(blank=True, choices=[('Director', 'Director'), ('Coordinador', 'Coordinador'), ('Enfermero', 'Enfermero')], max_length=20, verbose_name='Rol'),
        ),
    ]
