# Generated by Django 5.2.7 on 2025-12-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_alter_worker_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='shift',
            field=models.CharField(blank=True, choices=[('Mañana', 'Mañana'), ('Tarde', 'Tarde'), ('Noche', 'Noche')], max_length=20, verbose_name='Turno'),
        ),
    ]
