# Generated by Django 5.2.7 on 2025-12-09 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_worker_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='account_number',
            field=models.CharField(blank=True, max_length=29, verbose_name='Número de cuenta'),
        ),
    ]
