# Generated by Django 5.2.7 on 2025-11-25 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0002_worker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('time', models.TimeField(auto_now_add=True, verbose_name='Hora')),
                ('place', models.CharField(choices=[('habitacion', 'Habitación'), ('baño', 'Baño'), ('comedor', 'Comedor'), ('pasillo', 'Pasillo'), ('jardin', 'Jardín'), ('otro', 'Otro')], max_length=50, verbose_name='Lugar')),
                ('cause', models.TextField(blank=True, verbose_name='Causa')),
                ('consequences', models.TextField(blank=True, verbose_name='Consecuencias')),
                ('observations', models.TextField(blank=True, verbose_name='Observaciones')),
                ('family_informed', models.CharField(blank=True, max_length=200, verbose_name='Familiar informado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_falls', to='management.worker', verbose_name='Registrado por')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='falls', to='management.resident', verbose_name='Residente')),
            ],
            options={
                'verbose_name': 'Caída',
                'verbose_name_plural': 'Caídas',
                'ordering': ['-date', '-time'],
            },
        ),
    ]
